1. 어떤 경우에는 구체적으로 계산을 해보는 것이 이해하는데 도움이 된다. 다음과 같이 2개의 입력과 하나의 출력을 가지는 MLP에서 원하는 출력값이 0이라고 할 때, 각 뉴론의 출력값과 오차를 계산해보자.

활성화 함수는 계산을 간단히 하기 위하여 ReLU 함수라고 가정한다. 순방향 패스와 오차 값만을 계산해보자. (10점 만점)

힌트: 오차함수는 평균 제곱 오차(MSE)을 사용하세요.

힌트 2: 그림파일(4번째숙제_그림.png.jpg)을 참고하세요.

힌트 3: 코드를 이용하셔도 괜찮습니다.

![nn](4번째숙제_그림.png.jpg)

In [1]:
import numpy as np
#입력값
X = np.array([[1,1]])
#출력값
T = np.array([[0]])
def relu(x):
    return np.maximum(0, x)
def MSE(target, y):
    return 0.5 * np.sum((y-target) ** 2)
W1 = np.array([[0.8, 0.4, 0.3], 
               [0.2, 0.9, 0.5]])
W2 = np.array([[0.3], 
               [0.5], 
               [0.9]])

#B1 = np.array([[0.0, 0.0, 0.0]])
#B2 = np.array([[0.0]])   
def predict(x):
    layer0 = x
    Z1 = np.dot(layer0, W1) #+ B1
    layer1 = relu(Z1)
    Z2 = np.dot(layer1, W2) #+ B2
    layer2 = relu(Z2)
    return layer0, layer1, layer2
def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1))
        layer0, layer1, layer2 = predict(x)
        print('입력 = ', layer0)
        print('layer1 = ', layer1)
        print('출력값 = ', layer2)
        print('오차값 = ' ,MSE(T, layer2))

test()

입력 =  [[1 1]]
layer1 =  [[1.  1.3 0.8]]
출력값 =  [[1.67]]
오차값 =  1.39445



2. 본문의 MLP 파이썬 프로그램을 참조하여 4번의 신경망을 구현해보자. 활성화 함수는 ReLU 함수라고 가정한다. (5점 만점)

주의점: 학습률을 0.2에서 0.02로 변경하세요. 반복 학습횟수(에포크)를 10만번으로 변경하세요.

주의점2: 문제에서는 4번 문제를 구현하라고 써있으나, mlp2 코드에 써져있는 데이터(X,T,W,B)를 그대로 사용하세요.

주의점3: 여러분은 활성화 함수의 미분을 직접 코드로 구현하셔야합니다.

In [2]:
import numpy as np

def relu(x):
    return np.maximum(0, x)
def relu_deriv(x):
    return np.where(x > 0, 1, 0)

# 입력유닛의 개수, 은닉유닛의 개수, 출력유닛의 개수
inputs, hiddens, outputs = 2, 2, 1
learning_rate=0.02   			# 학습률 변경

# 훈련 샘플과 정답
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[1], [0], [0], [1]])

W1 = np.array([[0.10,0.20], [0.30,0.40]])
W2 = np.array([[0.50],[0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3])

# 순방향 전파 계산
def predict(x):
        layer0 = x			# 입력을 layer0에 대입한다. 
        Z1 = np.dot(layer0, W1)+B1	# 행렬의 곱을 계산한다. 
        layer1 = relu(Z1)		# 활성화 함수를 적용한다. 
        Z2 = np.dot(layer1, W2)+B2	# 행렬의 곱을 계산한다. 
        layer2 = relu(Z2)		# 활성화 함수를 적용한다. 
        return layer0, layer1, layer2

# 역방향 전파 계산
def fit():
    global W1, W2, B1, B2		# 우리는 외부에 정의된 변수를 변경해야 한다. 
    for i in range(100000):		# 10만번 반복한다. 
        for x, y in zip(X, T):		# 학습 샘플을 하나씩 꺼낸다. 
            x = np.reshape(x, (1, -1))	# 2차원 행렬로 만든다. ①
            y = np.reshape(y, (1, -1))	# 2차원 행렬로 만든다. 

            layer0, layer1, layer2 = predict(x)			# 순방향 계산
            layer2_error = layer2-y				# 오차 계산
            layer2_delta = layer2_error*relu_deriv(layer2)	# 출력층의 델타 계산 
            layer1_error = np.dot(layer2_delta, W2.T)		# 은닉층의 오차 계산 ②
            layer1_delta = layer1_error*relu_deriv(layer1)	# 은닉층의 델타 계산 ③
            
            W2 += -learning_rate*np.dot(layer1.T, layer2_delta)	# ④
            W1 += -learning_rate*np.dot(layer0.T, layer1_delta)	# 
            B2 += -learning_rate*np.sum(layer2_delta, axis=0)	# ⑤
            B1 += -learning_rate*np.sum(layer1_delta, axis=0)	# 

def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1))	# 하나의 샘플을 꺼내서 2차원 행렬로 만든다. 
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)		# 출력층의 값을 출력해본다. 

print('학습전 ===================================')        
test()        
print('학습후 ===================================')        
fit()
test()

학습전 ===================================
[[0 0]] [1] [[0.47]]
[[0 1]] [0] [[0.86]]
[[1 0]] [0] [[0.64]]
[[1 1]] [1] [[1.03]]
학습후 ===================================
[[0 0]] [1] [[1.]]
[[0 1]] [0] [[0.50505051]]
[[1 0]] [0] [[0.01010101]]
[[1 1]] [1] [[0.50505051]]


3. 본문의 MLP 파이썬 프로그램에서 다양한 활성화 함수를 사용하여서 학습이 어떻게 달라지는 지를 살펴보자. ReLU 함수와 Tanh 함수를 사용해보자. (5점 만점)

주의점: 학습률을 0.2에서 0.02로 변경하세요. 반복 학습횟수(에포크)를 10만번으로 변경하세요.

주의점2: 문제에서는 4번 문제를 구현하라고 써있으나, mlp2 코드에 써져있는 데이터(X,T,W,B)를 그대로 사용하세요.

주의점3: 여러분은 활성화 함수의 미분을 직접 코드로 구현하셔야합니다.

In [3]:
#relu함수
def relu(x):
    return np.maximum(0, x)
def relu_deriv(x):
    return np.where(x > 0, 1, 0)

#tanh함수
def tanh(x):
    return 2 / (1 + np.exp(-2 * x)) - 1

def tanh_deriv(x):
    return 4 * np.exp(-2 * x) / (1 + np.exp(-2 * x))**2

In [4]:
inputs, hiddens, outputs = 2, 2, 1
learning_rate=0.02   			# 학습률 변경

# 훈련 샘플과 정답
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[1], [0], [0], [1]])

W1 = np.array([[0.10,0.20], [0.30,0.40]])
W2 = np.array([[0.50],[0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3]) 

# 순방향 전파 계산
def predict(x):
        layer0 = x			# 입력을 layer0에 대입한다. 
        Z1 = np.dot(layer0, W1)+B1	# 행렬의 곱을 계산한다. 
        layer1 = relu(Z1)		# 활성화 함수를 적용한다. 
        Z2 = np.dot(layer1, W2)+B2	# 행렬의 곱을 계산한다. 
        layer2 = relu(Z2)		# 활성화 함수를 적용한다. 
        return layer0, layer1, layer2

# 역방향 전파 계산
def fit():
    global W1, W2, B1, B2		# 우리는 외부에 정의된 변수를 변경해야 한다. 
    for i in range(100000):		# 10만번 반복한다. 
        for x, y in zip(X, T):		# 학습 샘플을 하나씩 꺼낸다. 
            x = np.reshape(x, (1, -1))	# 2차원 행렬로 만든다. ①
            y = np.reshape(y, (1, -1))	# 2차원 행렬로 만든다. 

            layer0, layer1, layer2 = predict(x)			# 순방향 계산
            layer2_error = layer2-y				# 오차 계산
            layer2_delta = layer2_error*relu_deriv(layer2)	# 출력층의 델타 계산 
            layer1_error = np.dot(layer2_delta, W2.T)		# 은닉층의 오차 계산 ②
            layer1_delta = layer1_error*relu_deriv(layer1)	# 은닉층의 델타 계산 ③
            
            W2 += -learning_rate*np.dot(layer1.T, layer2_delta)	# ④
            W1 += -learning_rate*np.dot(layer0.T, layer1_delta)	# 
            B2 += -learning_rate*np.sum(layer2_delta, axis=0)	# ⑤
            B1 += -learning_rate*np.sum(layer1_delta, axis=0)	# 

def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1))	# 하나의 샘플을 꺼내서 2차원 행렬로 만든다. 
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)		# 출력층의 값을 출력해본다. 
        

print('활성화 함수 relu')
print('학습전 ===================================')        
test()        
print('학습후 ===================================')        
fit()
test()

활성화 함수 relu
학습전 ===================================
[[0 0]] [1] [[0.47]]
[[0 1]] [0] [[0.86]]
[[1 0]] [0] [[0.64]]
[[1 1]] [1] [[1.03]]
학습후 ===================================
[[0 0]] [1] [[1.]]
[[0 1]] [0] [[0.50505051]]
[[1 0]] [0] [[0.01010101]]
[[1 1]] [1] [[0.50505051]]


In [5]:
inputs, hiddens, outputs = 2, 3, 1
learning_rate=0.02   			# 학습률 변경

# 훈련 샘플과 정답
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
T = np.array([[1], [0], [0], [1]])

W1 = np.array([[0.10,0.20], [0.30,0.40]])
W2 = np.array([[0.50],[0.60]])
B1 = np.array([0.1, 0.2])
B2 = np.array([0.3]) 

# 순방향 전파 계산
def predict(x):
        layer0 = x			# 입력을 layer0에 대입한다. 
        Z1 = np.dot(layer0, W1)+B1	# 행렬의 곱을 계산한다. 
        layer1 = tanh(Z1)		# 활성화 함수를 적용한다. 
        Z2 = np.dot(layer1, W2)+B2	# 행렬의 곱을 계산한다. 
        layer2 = tanh(Z2)		# 활성화 함수를 적용한다. 
        return layer0, layer1, layer2

# 역방향 전파 계산
def fit():
    global W1, W2, B1, B2		# 우리는 외부에 정의된 변수를 변경해야 한다. 
    for i in range(100000):		# 10만번 반복한다. 
        for x, y in zip(X, T):		# 학습 샘플을 하나씩 꺼낸다. 
            x = np.reshape(x, (1, -1))	# 2차원 행렬로 만든다. ①
            y = np.reshape(y, (1, -1))	# 2차원 행렬로 만든다. 

            layer0, layer1, layer2 = predict(x)			# 순방향 계산
            layer2_error = layer2-y				# 오차 계산
            layer2_delta = layer2_error*tanh_deriv(layer2)	# 출력층의 델타 계산 
            layer1_error = np.dot(layer2_delta, W2.T)		# 은닉층의 오차 계산 ②
            layer1_delta = layer1_error*tanh_deriv(layer1)	# 은닉층의 델타 계산 ③
            
            W2 += -learning_rate*np.dot(layer1.T, layer2_delta)	# ④
            W1 += -learning_rate*np.dot(layer0.T, layer1_delta)	# 
            B2 += -learning_rate*np.sum(layer2_delta, axis=0)	# ⑤
            B1 += -learning_rate*np.sum(layer1_delta, axis=0)	# 

def test():
    for x, y in zip(X, T):
        x = np.reshape(x, (1, -1))	# 하나의 샘플을 꺼내서 2차원 행렬로 만든다. 
        layer0, layer1, layer2 = predict(x)
        print(x, y, layer2)		# 출력층의 값을 출력해본다. 

print('활성화 함수 tanh')
print('학습전 ===================================')        
test()        
print('학습후 ===================================')        
fit()
test()

활성화 함수 tanh
학습전 ===================================
[[0 0]] [1] [[0.4367917]]
[[0 1]] [0] [[0.67080442]]
[[1 0]] [0] [[0.55574603]]
[[1 1]] [1] [[0.73035166]]
학습후 ===================================
[[0 0]] [1] [[0.99971179]]
[[0 1]] [0] [[0.00010927]]
[[1 0]] [0] [[0.00011459]]
[[1 1]] [1] [[0.99973893]]
